name: Get Home Latest Timeline

on:
  schedule:
    - cron: '*/30 * * * *'  # 每30分钟运行
  workflow_dispatch:      # 允许手动触发

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout daily-posts branch
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: daily-posts # 检出 daily-posts 分支
    
      - name: Rebase daily-posts with main
        run: |
          git fetch origin main
          git rebase origin/main || (git rebase --abort && exit 1)
            
      - name: Setup Git
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
          
      - name: Install dependencies
        run: bun install
        
      - name: Run fetch script
        env:
          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
        run: bun run scripts/fetch-tweets.ts
        
      - name: Commit and push changes to daily-posts branch
        run: |
          git checkout -B daily-posts
          git add .
          git commit -m "chore: update user data [skip ci]" || exit 0
          git push origin daily-posts